### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by Amrhub** [Amrhub/healthCare-source#35]
- [x] Patient booking with a doctor,
- [x] Doctor can view all his patients and pending requests.
- [x] Doctor can view his patient's history and its location, ECG, and extra information about him
- [ ] Doctors home page.
- [ ] Admin can view doctor pending requests
- [ ] [OPTIONAL] Admin can view and adjust patients' devices connection

**Comment by Amrhub** [comment]
1
